# Generated by Django 2.2.9 on 2020-01-27 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Title', models.CharField(max_length=64)),
                ('Category_Image', models.FileField(upload_to='static/uploads/')),
                ('Category_slug', models.SlugField(blank=True, default='', max_length=32)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode_Title', models.CharField(max_length=32)),
                ('Episode_slug', models.SlugField(blank=True, default='', max_length=32)),
                ('Episode_TextStory', models.CharField(max_length=8000)),
                ('Episode_Image', models.FileField(blank=True, null=True, upload_to='static/uploads/')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Story_Title', models.CharField(max_length=32)),
                ('Story_slug', models.SlugField(blank=True, default='', max_length=32)),
                ('Story_Description', models.CharField(max_length=32)),
                ('Story_Image', models.FileField(upload_to='static/uploads/')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('FK_User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Story_Category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season_Title', models.CharField(max_length=32)),
                ('Season_slug', models.SlugField(blank=True, default='', max_length=32)),
                ('Season_Image', models.FileField(blank=True, null=True, upload_to='static/uploads/')),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('Fk_Story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Story')),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='EpisodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EpisodeReview_Rating', models.IntegerField()),
                ('EpisodeReview_Comment', models.CharField(max_length=1000)),
                ('EpisodeReview_slug', models.SlugField(blank=True, default='', max_length=32)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('EpisodeReview_Episode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Episode')),
                ('EpisodeReview_User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EpisodeReviews',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='Episode_Season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Season'),
        ),
    ]
