# Generated by Django 2.2.9 on 2020-01-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_FullName', models.CharField(blank=True, max_length=250, null=True)),
                ('User_photo', models.FileField(blank=True, null=True, upload_to='static/uploads/')),
                ('User_Bio', models.CharField(blank=True, max_length=250, null=True)),
                ('User_Country', models.CharField(max_length=250)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('UserProfile_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
